* Generated by CDO version 1.4.7
*
DSET  ^pdsi_future1seas.grb
DTYPE  GRIB
INDEX  ^pdsi_future1seas.gmp
XDEF 75 LINEAR -48.000000 0.187500
YDEF 86 LINEAR -18.000000 0.187494
ZDEF 1 LEVELS 0 
TDEF 97 LINEAR 00:00Z01feb2076 3mo
TITLE  pdsi_future1seas.grb  75x86 grid
UNDEF  -9e+33
VARS  1
var1               0  1,1  var1
ENDVARS
